inherit_from: "configs/rgbd/rawslam/base_config.yaml"

Dataset:
  dataset_path: "datasets/rawslam/coffee"
  raw: True
  pcd_downsample: 256
  Calibration:
    fx: 1380.4
    fy: 1379.3
    cx: 961.6
    cy: 568.1
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: True
    width: 1920
    height: 1080
    desired_width: 640
    desired_height: 360
    depth_scale: 1000 #0.0010000000474974513
  Resize:
    desired_width: 320
    desired_height: 180

Training:
  loss: "rawnerf"

mlp_opt_params:
  feature_lr_mlp_bias: 1e-4
  feature_lr_mlp_feat: 2e-3
  color_mlp_opt:
    type: TinyColorMLP
    in_feats: 16
    dir_feats: 3
    act: relu
    mid_feats_list: [16]
    out_feats: 3
    final_bias: ~
    final_act: torch.exp
  optim_color_mlp:
    lr: 1.0e-4
    weight_decay: 0
    betas: [0.9, 0.999]
  color_feat_opt:
    feat_len: 16
    feat_init_sigma: 0.001

pipeline_params:
  use_mlp: True
